version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app 
    ports:
      - "8010:8010"
    depends_on:
      - db
